# Generated by Django 3.0.3 on 2020-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitID', models.TextField()),
                ('devName', models.TextField()),
            ],
        ),
    ]
