# Generated by Django 3.0.3 on 2020-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0002_auto_20200305_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='builddata',
            name='publishDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='builddata',
            name='commitID',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='builddata',
            name='devName',
            field=models.CharField(max_length=120),
        ),
    ]
