# Generated by Django 3.0.3 on 2020-03-09 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0003_auto_20200309_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builddata',
            name='publishDate',
        ),
        migrations.AddField(
            model_name='builddata',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
