# Generated by Django 3.0.3 on 2020-03-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0004_auto_20200309_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builddata',
            options={'ordering': ['-timeStamp']},
        ),
    ]
